//! GENERATED by `cargo renzora sync` — do not edit.
//!
//! The Runtime-scope plugin list, one entry per `renzora::add!(..,
//! Runtime)` found under `crates/`. Edit the declaration in the plugin's
//! own crate, not this file; `cargo renzora sync --check` fails CI if
//! this file and those declarations disagree.
//!
//! A `#[cfg]` here mirrors the manifest: either the feature that enables
//! the crate's optional dependency, or a feature gating the module the
//! plugin is defined in. Ungated entries are always compiled in.

#![allow(clippy::default_constructed_unit_structs)]

use bevy::app::App;

/// Install every Runtime-scope plugin. Entries are ordered by the
/// `priority` given to `add!` (lower first, default 0), then by path.
pub(crate) fn add_runtime_plugins(app: &mut App) {
    #[cfg(feature = "localization")]
    app.add_plugins(renzora_lang::LangPlugin::default());
    #[cfg(feature = "animation")]
    app.add_plugins(renzora_animation::AnimationPlugin::default());
    #[cfg(feature = "antialiasing")]
    app.add_plugins(renzora_antialiasing::AntiAliasingPlugin::default());
    #[cfg(feature = "atmosphere")]
    app.add_plugins(renzora_atmosphere::AtmospherePlugin::default());
    #[cfg(feature = "audio")]
    app.add_plugins(renzora_audio::AudioPlugin::default());
    #[cfg(feature = "auto_exposure")]
    app.add_plugins(renzora_auto_exposure::AutoExposurePlugin::default());
    #[cfg(feature = "bloom")]
    app.add_plugins(renzora_bloom_effect::BloomEffectPlugin::default());
    #[cfg(feature = "blueprint")]
    app.add_plugins(renzora_blueprint::BlueprintPlugin::default());
    #[cfg(feature = "cloth")]
    app.add_plugins(renzora_cloth::ClothPlugin::default());
    #[cfg(feature = "clouds")]
    app.add_plugins(renzora_clouds::CloudsPlugin::default());
    #[cfg(feature = "distance_fog")]
    app.add_plugins(renzora_distance_fog::DistanceFogPlugin::default());
    #[cfg(feature = "dof")]
    app.add_plugins(renzora_dof::DepthOfFieldPlugin::default());
    #[cfg(feature = "ui")]
    #[cfg(feature = "game_ui")]
    app.add_plugins(renzora_ember::game_ui::GameUiPlugin::default());
    #[cfg(feature = "ui")]
    #[cfg(feature = "game_ui")]
    app.add_plugins(renzora_ember::markup::MarkupPlugin::default());
    #[cfg(feature = "environment_map")]
    app.add_plugins(renzora_environment_map::EnvironmentMapPlugin::default());
    #[cfg(feature = "forward_decal")]
    app.add_plugins(renzora_forward_decal::DecalPlugin::default());
    #[cfg(feature = "gaussian_splatting")]
    app.add_plugins(renzora_gaussian_splatting::GaussianSplatPlugin::default());
    #[cfg(feature = "particles")]
    app.add_plugins(renzora_hanabi::HanabiParticlePlugin::default());
    #[cfg(feature = "lens_distortion")]
    app.add_plugins(renzora_lens_distortion::LensDistortionPlugin::default());
    #[cfg(feature = "light2d")]
    app.add_plugins(renzora_light2d::Light2dPlugin::default());
    app.add_plugins(renzora_lighting::LightingPlugin::default());
    #[cfg(feature = "lumen")]
    app.add_plugins(renzora_lumen::LumenPlugin::default());
    #[cfg(feature = "motion_blur")]
    app.add_plugins(renzora_motion_blur::MotionBlurPlugin::default());
    app.add_plugins(renzora_native_plugin::NativePluginLoader::default());
    #[cfg(feature = "navmesh")]
    app.add_plugins(renzora_navmesh::NavMeshPlugin::default());
    app.add_plugins(renzora_net::NetPlugin::default());
    app.add_plugins(renzora_network::NetworkPlugin::default());
    #[cfg(feature = "night_stars")]
    app.add_plugins(renzora_night_stars::NightStarsPlugin::default());
    #[cfg(feature = "oit")]
    app.add_plugins(renzora_oit::OitPlugin::default());
    #[cfg(feature = "parkour")]
    app.add_plugins(renzora_parkour::ParkourPlugin::default());
    #[cfg(feature = "pool_water")]
    app.add_plugins(renzora_pool_water::PoolWaterPlugin::default());
    #[cfg(feature = "procedural_tree")]
    app.add_plugins(renzora_procedural_tree::ProceduralTreePlugin::default());
    #[cfg(feature = "ragdoll")]
    app.add_plugins(renzora_ragdoll::RagdollPlugin::default());
    app.add_plugins(renzora_rust_script::RustScriptPlugin::default());
    #[cfg(feature = "shader_graph")]
    app.add_plugins(renzora_shader::ShaderPlugin::default());
    #[cfg(feature = "shader_graph")]
    app.add_plugins(renzora_shader::material::MaterialPlugin::default());
    #[cfg(feature = "skybox")]
    app.add_plugins(renzora_skybox::SkyboxPlugin::default());
    #[cfg(feature = "solari")]
    app.add_plugins(renzora_solari::SolariPlugin::default());
    #[cfg(feature = "spline")]
    app.add_plugins(renzora_spline::SplinePlugin::default());
    #[cfg(feature = "sprite_anim")]
    app.add_plugins(renzora_sprite_anim::SpriteImagesPlugin::default());
    #[cfg(feature = "ssao")]
    app.add_plugins(renzora_ssao::SsaoPlugin::default());
    #[cfg(feature = "ssr")]
    app.add_plugins(renzora_ssr::SsrPlugin::default());
    #[cfg(feature = "terrain")]
    app.add_plugins(renzora_terrain::TerrainPlugin::default());
    #[cfg(feature = "terrain")]
    app.add_plugins(renzora_terrain::foliage::FoliagePlugin::default());
    #[cfg(feature = "text3d")]
    app.add_plugins(renzora_text3d::Text3dPlugin::default());
    #[cfg(feature = "tilemap")]
    app.add_plugins(renzora_tilemap::TilemapPlugin::default());
    app.add_plugins(renzora_tonemapping::TonemappingPlugin::default());
    #[cfg(feature = "vignette")]
    app.add_plugins(renzora_vignette::VignettePlugin::default());
    #[cfg(feature = "volumetric_fog")]
    app.add_plugins(renzora_volumetric_fog::VolumetricFogPlugin::default());
    #[cfg(feature = "water")]
    app.add_plugins(renzora_water::WaterPlugin::default());
    app.add_plugins(renzora_wind::WindPlugin::default());
}
