//! GENERATED by `cargo renzora sync` — do not edit.
//!
//! The Editor-scope plugin list, one entry per `renzora::add!(..,
//! Editor)` found under `crates/`. Edit the declaration in the plugin's
//! own crate, not this file; `cargo renzora sync --check` fails CI if
//! this file and those declarations disagree.
//!
//! A `#[cfg]` here mirrors the manifest: either the feature that enables
//! the crate's optional dependency, or a feature gating the module the
//! plugin is defined in. Ungated entries are always compiled in.

#![allow(clippy::default_constructed_unit_structs)]

use renzora::bevy::app::App;

/// Install every Editor-scope plugin. Entries are ordered by the
/// `priority` given to `add!` (lower first, default 0), then by path.
pub(crate) fn add_editor_plugins(app: &mut App) {
    app.add_plugins(renzora_animation_editor::AnimationEditorPlugin::default());
    app.add_plugins(renzora_antialiasing_editor::AntiAliasingEditorPlugin::default());
    app.add_plugins(renzora_asset_browser::AssetBrowserPlugin::default());
    app.add_plugins(renzora_atmosphere_editor::AtmosphereEditorPlugin::default());
    app.add_plugins(renzora_auto_exposure_editor::AutoExposureEditorPlugin::default());
    app.add_plugins(renzora_autosave::AutoSavePlugin::default());
    app.add_plugins(renzora_bloom_effect_editor::BloomEditorPlugin::default());
    app.add_plugins(renzora_blueprint_editor::BlueprintEditorPlugin::default());
    app.add_plugins(renzora_camera::CameraPlugin::default());
    app.add_plugins(renzora_clouds_editor::CloudsEditorPlugin::default());
    app.add_plugins(renzora_code_editor::CodeEditorPlugin::default());
    app.add_plugins(renzora_command_palette::CommandPalettePlugin::default());
    app.add_plugins(renzora_console::ConsolePlugin::default());
    app.add_plugins(renzora_context_menu::ContextMenuPlugin::default());
    app.add_plugins(renzora_debugger::DebuggerPlugin::default());
    app.add_plugins(renzora_distance_fog_editor::DistanceFogEditorPlugin::default());
    app.add_plugins(renzora_dof_editor::DepthOfFieldEditorPlugin::default());
    app.add_plugins(renzora_ember_editor::HuiEditorBundlePlugin::default());
    app.add_plugins(renzora_ember_editor::game_ui::GameUiEditorPlugin::default());
    app.add_plugins(renzora_engine_editor::EngineEditorPlugin::default());
    app.add_plugins(renzora_engine_plugins::EnginePluginEcsPlugin::default());
    app.add_plugins(renzora_environment_map_editor::EnvironmentMapEditorPlugin::default());
    app.add_plugins(renzora_export::ExportPlugin::default());
    app.add_plugins(renzora_foliage_editor::FoliageEditorPlugin::default());
    app.add_plugins(renzora_forward_decal_editor::DecalEditorPlugin::default());
    app.add_plugins(renzora_gamepad_editor::GamepadEditorPlugin::default());
    app.add_plugins(renzora_gizmo::GizmoPlugin::default());
    app.add_plugins(renzora_grid::GridPlugin::default());
    app.add_plugins(renzora_hierarchy::HierarchyPanelPlugin::default());
    app.add_plugins(renzora_history::HistoryPanelPlugin::default());
    app.add_plugins(renzora_import_ui::ImportPlugin::default());
    app.add_plugins(renzora_inspector::InspectorPanelPlugin::default());
    app.add_plugins(renzora_lens_distortion_editor::LensDistortionEditorPlugin::default());
    app.add_plugins(renzora_level_presets::LevelPresetsPlugin::default());
    app.add_plugins(renzora_lighting_editor::LightingEditorPlugin::default());
    app.add_plugins(renzora_marketplace::MarketplacePlugin::default());
    app.add_plugins(renzora_material_editor::MaterialEditorPlugin::default());
    app.add_plugins(renzora_mesh_edit::MeshEditPlugin::default());
    app.add_plugins(renzora_mixer::MixerPlugin::default());
    app.add_plugins(renzora_motion_blur_editor::MotionBlurEditorPlugin::default());
    app.add_plugins(renzora_navmesh_editor::NavMeshEditorPlugin::default());
    app.add_plugins(renzora_network_editor::NetworkEditorPlugin::default());
    app.add_plugins(renzora_night_stars_editor::NightStarsEditorPlugin::default());
    app.add_plugins(renzora_oit_editor::OitEditorPlugin::default());
    app.add_plugins(renzora_parkour_editor::ParkourEditorPlugin::default());
    app.add_plugins(renzora_particle_editor::ParticleEditorPlugin::default());
    app.add_plugins(renzora_physics_editor::PhysicsEditorPlugin::default());
    app.add_plugins(renzora_pool_water_editor::PoolWaterEditorPlugin::default());
    app.add_plugins(renzora_procedural_tree_editor::ProceduralTreeEditorPlugin::default());
    app.add_plugins(renzora_scene::ScenePlugin::default());
    app.add_plugins(renzora_scripting_editor::ScriptingEditorPlugin::default());
    app.add_plugins(renzora_settings::SettingsPlugin::default());
    app.add_plugins(renzora_shader_editor::ShaderEditorPlugin::default());
    app.add_plugins(renzora_shape_library::ShapeLibraryPlugin::default());
    app.add_plugins(renzora_shell::ShellPlugin::default());
    app.add_plugins(renzora_skybox_editor::SkyboxEditorPlugin::default());
    app.add_plugins(renzora_splash::SplashPlugin::default());
    app.add_plugins(renzora_sprite_anim_editor::SpriteAnimEditorPlugin::default());
    app.add_plugins(renzora_ssao_editor::SsaoEditorPlugin::default());
    app.add_plugins(renzora_ssr_editor::SsrEditorPlugin::default());
    app.add_plugins(renzora_system_monitor::SystemMonitorPlugin::default());
    app.add_plugins(renzora_terrain_editor::TerrainEditorPlugin::default());
    app.add_plugins(renzora_test_component::TestComponentPlugin::default());
    app.add_plugins(renzora_text3d_editor::Text3dEditorPlugin::default());
    app.add_plugins(renzora_theme_status::ThemeStatusPlugin::default());
    app.add_plugins(renzora_tilemap_editor::TilemapEditorPlugin::default());
    app.add_plugins(renzora_tonemapping_editor::TonemappingEditorPlugin::default());
    app.add_plugins(renzora_tutorial::TutorialPlugin::default());
    app.add_plugins(renzora_undo::UndoPlugin::default());
    app.add_plugins(renzora_update::UpdatePlugin::default());
    app.add_plugins(renzora_viewport::ViewportPlugin::default());
    app.add_plugins(renzora_vignette_editor::VignetteEditorPlugin::default());
    app.add_plugins(renzora_volumetric_fog_editor::VolumetricFogEditorPlugin::default());
    app.add_plugins(renzora_water_editor::WaterEditorPlugin::default());
    app.add_plugins(renzora_wind_editor::WindEditorPlugin::default());
}
