//! End-to-end test for the lean export's generated crate.
//!
//! Builds a synthetic project tree, calls the production
//! `stage_static_scripts`, and then runs `cargo check --profile dist`
//! against the generated workspace. The test assembles the workspace
//! by symlinking the engine's `renzora`, `renzora_identity`, and their
//! transitive path deps (`renzora_macros`, `renzora_plugin`,
//! `renzora_plugin_derive`) into the generated workspace's `crates/`
//! directory, exactly mirroring the layout a real lean export sees
//! after `renzora_export::build::stage_static_scripts` writes the
//! crate.

use std::fs;
use std::path::PathBuf;
use std::process::Command;

fn script_body() -> &'static str {
    "fn update(_: &mut renzora::ScriptCtx) {}\nrenzora::script!(update);\n"
}

/// Build the path-dep closure of `renzora` and `renzora_identity`.
fn transitive_path_deps() -> &'static [&'static str] {
    &[
        "renzora",
        "renzora_identity",
        "renzora_plugin",
        "renzora_plugin_derive",
        "renzora_macros",
    ]
}

/// Symlink each engine crate name into the generated workspace's
/// `crates/` directory. Cargo's resolver will find them via the
/// generated crate's `path = "../renzora"` etc.
fn symlink_required_crates(target_dir: &std::path::Path, engine_crates_dir: &std::path::Path) {
    for name in transitive_path_deps() {
        let from = engine_crates_dir.join(name);
        if !from.is_dir() {
            panic!("engine crate {name} not found at {}", from.display());
        }
        let to = target_dir.join(name);
        let _ = fs::remove_file(&to);
        std::os::unix::fs::symlink(&from, &to).expect("symlink engine crate");
    }
}

#[test]
fn generated_lean_crate_compiles_in_assembled_workspace() {
    let cargo_available = Command::new("cargo")
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false);
    if !cargo_available {
        eprintln!("cargo not on PATH — skipping");
        return;
    }

    // 1. Build a synthetic project tree with two scripts.
    let tmp = tempfile::tempdir().unwrap();
    let project = tmp.path();
    fs::create_dir_all(project.join("enemy")).unwrap();
    fs::write(project.join("enemy/spin.rs"), script_body()).unwrap();
    fs::create_dir_all(project.join("props")).unwrap();
    fs::write(project.join("props/spin.rs"), script_body()).unwrap();

    // 2. Generate the lean export into a copy_root.
    let copy_root = project.join("export");
    fs::create_dir_all(&copy_root).unwrap();
    let mut progress = |_s: String| {};
    let wrote = renzora_export::build::stage_static_scripts_for_test(
        project,
        &copy_root,
        &mut progress,
    )
    .expect("stage_static_scripts");
    assert!(wrote, "stage_static_scripts must return true");

    // 3. Build the assembled workspace: copy_root/crates/renzora_static_scripts
    //    was generated by the exporter; we symlink the engine source for
    //    every crate the generated manifest references by relative path.
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let engine_root = manifest_dir
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .canonicalize()
        .unwrap();
    let engine_crates_dir = engine_root.join("crates");

    let gen_crates_dir = copy_root.join("crates");
    fs::create_dir_all(&gen_crates_dir).unwrap();
    symlink_required_crates(&gen_crates_dir, &engine_crates_dir);

    // 4. Inject a workspace Cargo.toml into copy_root that provides the
    //    Bevy version the generated crate expects and the dist profile.
    let workspace_toml = "[workspace]\n\
         members = [\"crates/renzora_static_scripts\"]\n\
         resolver = \"2\"\n\
         \n\
         [workspace.lints]\n\
         \n\
         [workspace.dependencies]\n\
         renzora = { path = \"crates/renzora\", default-features = false }\n\
         renzora_identity = { path = \"crates/renzora_identity\" }\n\
         bevy = \"0.19\"\n\
         \n\
         [profile.dist]\n\
         inherits = \"release\"\n\
         opt-level = 2\n\
         lto = false\n";
    fs::write(copy_root.join("Cargo.toml"), workspace_toml).unwrap();

    // 5. Run `cargo check --profile dist` on the generated workspace.
    let target_dir = copy_root.join("target");
    let output = Command::new("cargo")
        .args(["check", "--profile", "dist"])
        .current_dir(&copy_root)
        .env("CARGO_TARGET_DIR", &target_dir)
        .env_remove("RUSTC_WRAPPER")
        .output()
        .expect("cargo check spawn");
    assert!(
        output.status.success(),
        "cargo check on the generated lean crate must succeed.\n--- stdout ---\n{}\n--- stderr ---\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}
