//! Plugin wiring generator — turns `renzora::add!` declarations into real
//! dependency edges and install lists.
//!
//! Drop a crate into `crates/` with `renzora::add!(MyPlugin);` in it and it is
//! part of the engine. That is the whole contract, and this module is what makes
//! it true, because cargo will not do it on its own: `[workspace] members`
//! accepts the glob `crates/renzora_*`, but `[dependencies]` has no glob and a
//! `build.rs` cannot add one (cargo resolves the dependency graph before build
//! scripts run). Something has to write that dependency line. This is that
//! something.
//!
//! It runs at the start of every `cargo renzora` build, and standalone as
//! `cargo renzora sync`. For each of the two hosts — `renzora_runtime` (Runtime
//! scope) and `renzora_editor` (Editor scope) — it writes:
//!
//! 1. a generated block inside `[dependencies]` holding one entry per declared
//!    plugin crate that isn't already listed by hand, and
//! 2. `src/plugins.rs`, an ordinary list of `app.add_plugins(...)` calls.
//!
//! Both outputs are committed, so a plain `cargo build`/`cargo check` never
//! needs this to have run. `cargo renzora sync --check` regenerates into memory
//! and fails if the result differs from what's on disk — that is the CI gate
//! that stops a stale list from shipping, and the reason a generated list is
//! safer than a hand-maintained one: it cannot silently omit a plugin.
//!
//! ## What replaced what
//!
//! `add!` used to submit an `inventory` entry that the host discovered at
//! startup. That indirection was for `dlopen`'d plugins, which no longer exist
//! in this form (the editor is a binary; third-party extensions are C-ABI
//! plugins that link no Bevy). Its removal also removed three separate
//! dead-strip workarounds whose only job was keeping the registry's
//! constructors alive: a keepalive `build.rs` in each host, and the
//! `renzora_static_plugins` aggregator for lean exports. A named type in a
//! generated list is visible to the linker; none of that scaffolding is needed.
//!
//! ## Feature gates are deliberately NOT generated
//!
//! Which plugins a lean export can strip, and how they group (`postfx` covers
//! eleven crates, `sky` five), is an editorial decision the source can't state.
//! So a newly discovered crate gets a plain, non-optional dependency: it is
//! always compiled and always installed. Making it strippable is a deliberate
//! follow-up — move its entry out of the generated block, mark it
//! `optional = true`, and add it to a feature. The generator then finds the
//! existing entry, leaves it alone, and reads the gate back out of the manifest
//! to emit the matching `#[cfg(feature = "...")]` in `plugins.rs`.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

const BEGIN: &str = "# ── generated by `cargo renzora sync` — declared plugin crates ──";
const END: &str = "# ── end generated ──";

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Scope {
    Runtime,
    Editor,
}

/// One `renzora::add!` declaration, resolved to everything the generator needs.
#[derive(Debug)]
struct Decl {
    /// Package name (`renzora_shader`), which is also the dependency key.
    pkg: String,
    /// Dependency path relative to a host manifest (`../renzora_shader`).
    dep_path: String,
    /// Fully-qualified plugin type (`renzora_shader::material::MaterialPlugin`).
    path: String,
    /// Crate-local features gating the module the declaration sits in, if any.
    /// A `#[cfg(feature = "game_ui")] pub mod game_ui;` means the plugin type
    /// only exists when that feature is on, so the install line needs a gate too.
    module_features: Vec<String>,
    scope: Scope,
    priority: i32,
    /// `crates/foo/src/lib.rs:166`, for error messages.
    site: String,
}

/// Regenerate the wiring. `check` reports drift instead of writing.
pub fn sync(repo: &Path, check: bool) -> Result<(), String> {
    if !check {
        heal(repo)?;
    }
    let decls = scan(repo)?;
    let runtime = Host {
        dir: repo.join("crates").join("renzora_runtime"),
        scope: Scope::Runtime,
        install_fn: "add_runtime_plugins",
        app_path: "bevy::app::App",
        // The runtime host is compiled unconditionally, so every gate is real.
        always: None,
    };
    let editor = Host {
        dir: repo.join("crates").join("renzora_editor"),
        scope: Scope::Editor,
        install_fn: "add_editor_plugins",
        // renzora_editor doesn't depend on bevy directly; it reaches it through
        // the contract crate like every other editor crate does.
        app_path: "renzora::bevy::app::App",
        // The whole module is already behind `editor`, so re-stating that gate
        // on every line would be noise.
        always: Some("editor"),
    };

    let mut changed = Vec::new();
    for host in [runtime, editor] {
        changed.extend(host.write(&decls, check)?);
    }

    if check && !changed.is_empty() {
        return Err(format!(
            "plugin wiring is stale — run `cargo renzora sync` and commit:\n  {}",
            changed.join("\n  ")
        ));
    }
    if !check {
        let n = decls.len();
        if changed.is_empty() {
            println!("[sync] {n} plugin declarations, wiring up to date");
        } else {
            for f in &changed {
                println!("[sync] wrote {f}");
            }
            println!("[sync] {n} plugin declarations");
        }
    }
    Ok(())
}

/// Prune references to plugin crates whose directory no longer exists.
///
/// This is the repair for someone deleting `crates/renzora_foo` by hand instead
/// of with [`remove`]. Cargo will not load a workspace holding a `path`
/// dependency on a missing directory — which is why xtask is its own workspace
/// root (see its `Cargo.toml`), so that this runs at all in that state.
///
/// Only entries pointing at an absent directory are touched, so there is nothing
/// to get wrong: a dependency that resolves is never a candidate.
fn heal(repo: &Path) -> Result<(), String> {
    for host in ["renzora_runtime", "renzora_editor"] {
        let path = repo.join("crates").join(host).join("Cargo.toml");
        let mut text = read(&path)?;
        let mut healed = Vec::new();
        for (name, dep) in path_deps(&text) {
            // Dependency paths are relative to the manifest holding them.
            if path.parent().map(|d| d.join(&dep).is_dir()) == Some(false) {
                text = prune_references(&text, &name);
                healed.push(name);
            }
        }
        if healed.is_empty() {
            continue;
        }
        std::fs::write(&path, text.replace('\n', "\r\n"))
            .map_err(|e| format!("write {}: {e}", path.display()))?;
        println!(
            "[sync] {host}: dropped {} deleted crate(s): {}",
            healed.len(),
            healed.join(", ")
        );
    }
    Ok(())
}

/// `(name, path)` for every `[dependencies]` entry declaring a `path = "..."`.
fn path_deps(text: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    let mut in_deps = false;
    for line in text.lines() {
        let t = line.trim();
        if t.starts_with('[') && !t.starts_with("[[") {
            in_deps = t == "[dependencies]";
            continue;
        }
        if !in_deps || t.starts_with('#') || t.is_empty() {
            continue;
        }
        let Some((name, rest)) = t.split_once('=') else {
            continue;
        };
        let Some(after) = rest.split_once("path").and_then(|(_, r)| r.split_once('"')) else {
            continue;
        };
        let Some((dep, _)) = after.1.split_once('"') else {
            continue;
        };
        out.push((name.trim().to_string(), dep.to_string()));
    }
    out
}

/// Delete a plugin crate and every reference to it, then re-sync.
///
/// Ordering is the whole point: cargo cannot load a workspace whose manifest
/// names a dependency directory that isn't there, so it could not even build
/// this tool to repair the damage afterwards. Everything happens in one process
/// — references first, directory second — so cargo only ever observes the state
/// before or the state after.
///
/// Unlike [`sync`], this prunes references *anywhere* in a host manifest, not
/// just inside the generated block. A plugin that was hand-moved out of the
/// block to become feature-gated (see the module docs) has a dependency entry
/// and one or more `dep:`/`crate/feature` items that regeneration deliberately
/// leaves alone; on deletion those are exactly what would be left dangling.
pub fn remove(repo: &Path, name: &str) -> Result<(), String> {
    let dir = repo.join("crates").join(name);
    if !dir.join("Cargo.toml").is_file() {
        return Err(format!("no crate at {}", dir.display()));
    }

    for host in ["renzora_runtime", "renzora_editor"] {
        let path = repo.join("crates").join(host).join("Cargo.toml");
        let text = read(&path)?;
        let pruned = prune_references(&text, name);
        if pruned != text {
            std::fs::write(&path, pruned.replace('\n', "\r\n"))
                .map_err(|e| format!("write {}: {e}", path.display()))?;
            println!("[sync] pruned {name} from {host}/Cargo.toml");
        }
    }

    std::fs::remove_dir_all(&dir).map_err(|e| format!("remove {}: {e}", dir.display()))?;
    println!("[sync] removed {}", dir.display());

    sync(repo, false)
}

/// Drop `name`'s dependency entry and every feature item that mentions it, then
/// clean up the features that leaves behind.
///
/// The cleanup needs a fixed point, not one pass. Removing `dep:renzora_probe`
/// empties `probe = ["dep:renzora_probe"]`, and a feature definition that is
/// gone must also stop being *referenced* — `default = [.., "probe", ..]` would
/// otherwise name a feature that no longer exists, which cargo rejects. Removing
/// it from `default` can in turn empty something else, so this repeats until
/// nothing changes.
///
/// Only features this pass emptied are removed. Several features are
/// legitimately empty by design (`profiling = []` is a pure code gate with no
/// dependencies), and deleting those would be a silent behaviour change.
fn prune_references(text: &str, name: &str) -> String {
    // Which features are already empty, so they're never mistaken for casualties.
    let empty_before: Vec<String> = feature_table(text)
        .0
        .into_iter()
        .filter(|(_, items)| items.is_empty())
        .map(|(n, _)| n)
        .collect();

    let mut out = drop_dep(text, name);
    out = drop_items(&out, |i| item_mentions(i, name));

    loop {
        let dead: Vec<String> = feature_table(&out)
            .0
            .into_iter()
            .filter(|(n, items)| items.is_empty() && !empty_before.contains(n))
            .map(|(n, _)| n)
            .collect();
        if dead.is_empty() {
            return out;
        }
        out = drop_items(&out, |i| dead.iter().any(|d| d == i));
        out = drop_definitions(&out, &dead);
    }
}

/// Remove `name`'s entry from `[dependencies]`. The trailing space/`=` is what
/// keeps `renzora_probe` from also matching `renzora_probe_extra`.
fn drop_dep(text: &str, name: &str) -> String {
    let mut out = String::new();
    let mut in_deps = false;
    for line in text.lines() {
        let t = line.trim();
        if t.starts_with('[') && !t.starts_with("[[") {
            in_deps = t == "[dependencies]";
        }
        if in_deps && (t.starts_with(&format!("{name} ")) || t.starts_with(&format!("{name}="))) {
            continue;
        }
        out.push_str(line);
        out.push('\n');
    }
    out
}

/// Remove every `[features]` item matching `pred`, keeping the definitions.
fn drop_items(text: &str, pred: impl Fn(&str) -> bool) -> String {
    let mut out = String::new();
    let mut in_features = false;
    for line in text.lines() {
        let t = line.trim();
        if t.starts_with('[') && !t.starts_with("[[") {
            in_features = t == "[features]";
        }
        if in_features && !t.starts_with('#') && !t.is_empty() {
            match t.split_once('=') {
                // A whole single-line definition: keep the key, filter the array.
                Some((key, body)) if body.trim_start().starts_with('[') && body.contains(']') => {
                    let kept: Vec<String> = split_items(body)
                        .into_iter()
                        .filter(|i| !pred(i))
                        .map(|i| format!("\"{i}\""))
                        .collect();
                    let _ = writeln!(out, "{} = [{}]", key.trim(), kept.join(", "));
                    continue;
                }
                // A bare item on its own line inside a multi-line array.
                None if split_items(t).iter().any(|i| pred(i)) => continue,
                _ => {}
            }
        }
        out.push_str(line);
        out.push('\n');
    }
    out
}

/// Delete the named feature definitions outright (single-line only — a
/// multi-line definition cannot have been emptied without its items going
/// first, which collapses it to one line).
fn drop_definitions(text: &str, names: &[String]) -> String {
    let mut out = String::new();
    let mut in_features = false;
    for line in text.lines() {
        let t = line.trim();
        if t.starts_with('[') && !t.starts_with("[[") {
            in_features = t == "[features]";
        }
        if in_features {
            if let Some((key, _)) = t.split_once('=') {
                if names.iter().any(|n| n == key.trim()) {
                    continue;
                }
            }
        }
        out.push_str(line);
        out.push('\n');
    }
    out
}

/// `dep:<name>`, `<name>/feat` or `<name>?/feat` — never a longer crate name
/// that merely starts the same way.
fn item_mentions(item: &str, name: &str) -> bool {
    item == format!("dep:{name}")
        || item.starts_with(&format!("{name}/"))
        || item.starts_with(&format!("{name}?/"))
}

// ── Scanning ────────────────────────────────────────────────────────────────

/// Find every built-in declaration plus the exact Tier 2 crates registered by
/// an immutable overlay workspace.
///
/// Built-ins are discovered under `crates/`. Tier 2 inputs are never found by a
/// broad filesystem walk: the immutable overlay names each exact runtime and
/// editor crate in `tier2/plugins.toml`. `plugins/` remains the separate C-ABI
/// tier and is never linked into either engine executable.
fn scan(repo: &Path) -> Result<Vec<Decl>, String> {
    let crates = repo.join("crates");
    let mut out = Vec::new();
    for dir in crate_dirs(&crates)? {
        let Some(pkg) = package_name(&read(&dir.join("Cargo.toml"))?) else {
            continue;
        };
        if !pkg.starts_with("renzora") {
            continue;
        }
        scan_crate(repo, &dir, None, &mut out)?;
    }

    for registered in tier2_crates(repo)? {
        let before = out.len();
        scan_crate(repo, &registered.dir, Some(registered.scope), &mut out)?;
        if out.len() == before {
            return Err(format!(
                "Tier 2 {:?} crate for `{}` has no top-level renzora::add! declaration: {}",
                registered.scope,
                registered.id,
                rel_display(repo, &registered.dir)
            ));
        }
    }

    // Deterministic output: priority first (the only ordering `add!` can express),
    // then alphabetical so an unrelated edit never reshuffles the file.
    out.sort_by(|a, b| {
        a.priority
            .cmp(&b.priority)
            .then_with(|| a.path.cmp(&b.path))
    });

    // Two declarations of one plugin would install it twice, and Bevy panics on
    // that at startup ("plugin was already added") — a runtime failure for a
    // mistake that is visible right here.
    for pair in out.windows(2) {
        if pair[0].path == pair[1].path {
            return Err(format!(
                "{} is declared twice:\n  {}\n  {}",
                pair[0].path, pair[0].site, pair[1].site
            ));
        }
    }
    let mut packages = BTreeMap::<&str, &str>::new();
    for decl in &out {
        if let Some(first) = packages.insert(&decl.pkg, &decl.dep_path) {
            if first != decl.dep_path {
                return Err(format!(
                    "package name `{}` resolves to both `{first}` and `{}`",
                    decl.pkg, decl.dep_path
                ));
            }
        }
    }
    Ok(out)
}

fn scan_crate(
    repo: &Path,
    dir: &Path,
    expected_scope: Option<Scope>,
    out: &mut Vec<Decl>,
) -> Result<(), String> {
    let manifest = dir.join("Cargo.toml");
    let pkg = package_name(&read(&manifest)?)
        .ok_or_else(|| format!("{} has no [package] name", manifest.display()))?;
    let src = dir.join("src");
    if !src.is_dir() {
        return Ok(());
    }
    let mod_gates = module_gates(&src)?;
    for file in rust_files(&src)? {
        let rel_mod = module_path(&src, &file);
        let text = read(&file)?;
        for (lineno, line) in text.lines().enumerate() {
            let Some(args) = declaration(line) else {
                continue;
            };
            let (ty, scope, priority) =
                parse_args(&args).map_err(|e| format!("{}:{}: {e}", file.display(), lineno + 1))?;
            if expected_scope.is_some_and(|expected| expected != scope) {
                return Err(format!(
                    "{}:{}: Tier 2 {:?} crate declares a {:?} plugin",
                    rel_display(repo, &file),
                    lineno + 1,
                    expected_scope.expect("checked above"),
                    scope
                ));
            }
            let mut path = pkg.clone();
            if !rel_mod.is_empty() {
                path.push_str("::");
                path.push_str(&rel_mod);
            }
            path.push_str("::");
            path.push_str(&ty);
            out.push(Decl {
                pkg: pkg.clone(),
                dep_path: dependency_path(repo, dir)?,
                path,
                module_features: gates_for(&mod_gates, &rel_mod),
                scope,
                priority,
                site: format!("{}:{}", rel_display(repo, &file), lineno + 1),
            });
        }
    }
    Ok(())
}

struct Tier2Crate {
    id: String,
    scope: Scope,
    dir: PathBuf,
}

/// Read the deliberately tiny generated registry without making xtask depend
/// on a TOML stack. Unknown fields are rejected so format changes fail closed.
fn tier2_crates(repo: &Path) -> Result<Vec<Tier2Crate>, String> {
    let path = repo.join("tier2/plugins.toml");
    if !path.is_file() {
        return Ok(Vec::new());
    }
    let text = read(&path)?;
    let mut schema = None;
    let mut entries: Vec<BTreeMap<String, String>> = Vec::new();
    for (line_number, line) in text.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if line == "[[plugin]]" {
            entries.push(BTreeMap::new());
            continue;
        }
        let (key, raw) = line.split_once('=').ok_or_else(|| {
            format!(
                "{}:{}: expected key = value",
                path.display(),
                line_number + 1
            )
        })?;
        let key = key.trim();
        let raw = raw.trim();
        if entries.is_empty() {
            if key != "schema" || schema.replace(raw.to_string()).is_some() {
                return Err(format!(
                    "{}:{}: invalid registry header",
                    path.display(),
                    line_number + 1
                ));
            }
            continue;
        }
        if !matches!(key, "id" | "runtime" | "editor") {
            return Err(format!(
                "{}:{}: unknown plugin field `{key}`",
                path.display(),
                line_number + 1
            ));
        }
        let value = quoted_value(raw).ok_or_else(|| {
            format!(
                "{}:{}: expected a quoted string",
                path.display(),
                line_number + 1
            )
        })?;
        if entries
            .last_mut()
            .expect("entry exists")
            .insert(key.to_string(), value)
            .is_some()
        {
            return Err(format!(
                "{}:{}: duplicate `{key}` field",
                path.display(),
                line_number + 1
            ));
        }
    }
    if schema.as_deref() != Some("1") {
        return Err(format!("{}: unsupported or missing schema", path.display()));
    }

    let mut out = Vec::new();
    for mut entry in entries {
        let id = entry
            .remove("id")
            .filter(|id| !id.is_empty())
            .ok_or_else(|| format!("{}: plugin entry has no id", path.display()))?;
        for (key, scope) in [("runtime", Scope::Runtime), ("editor", Scope::Editor)] {
            let Some(relative) = entry.remove(key) else {
                continue;
            };
            let relative_path = safe_registry_path(&relative)?;
            let dir = repo.join(&relative_path);
            if !dir.join("Cargo.toml").is_file() {
                return Err(format!(
                    "{}: `{id}` {key} crate is missing at {}",
                    path.display(),
                    dir.display()
                ));
            }
            out.push(Tier2Crate {
                id: id.clone(),
                scope,
                dir,
            });
        }
        if !entry.is_empty() {
            return Err(format!("{}: unconsumed plugin fields", path.display()));
        }
    }
    Ok(out)
}

fn quoted_value(raw: &str) -> Option<String> {
    raw.strip_prefix('"')?.strip_suffix('"').map(str::to_string)
}

fn safe_registry_path(value: &str) -> Result<PathBuf, String> {
    if !value.starts_with("tier2/") || value.contains('\\') {
        return Err(format!("unsafe Tier 2 registry path `{value}`"));
    }
    let mut path = PathBuf::new();
    for part in value.split('/') {
        if part.is_empty() || matches!(part, "." | "..") {
            return Err(format!("unsafe Tier 2 registry path `{value}`"));
        }
        path.push(part);
    }
    Ok(path)
}

/// Match a top-level `renzora::add!(...);` line, rejecting anything embedded in
/// a comment or a string. Requiring the closing `);` is what skips the doc
/// examples in `plugin_meta.rs` and the macro's own name inside a help string.
fn declaration(line: &str) -> Option<String> {
    let t = line.trim();
    let rest = t
        .strip_prefix("renzora::add!(")
        .or_else(|| t.strip_prefix("crate::add!("))?;
    let args = rest.strip_suffix(");")?;
    Some(args.to_string())
}

/// `MyPlugin` / `MyPlugin, Editor` / `MyPlugin, Runtime, priority = -50`.
fn parse_args(args: &str) -> Result<(String, Scope, i32), String> {
    let mut parts = args.split(',').map(str::trim);
    let ty = parts
        .next()
        .filter(|s| !s.is_empty())
        .ok_or("add! needs a plugin type")?
        .to_string();
    let mut scope = Scope::Runtime;
    let mut priority = 0i32;
    for part in parts {
        if let Some(p) = part.strip_prefix("priority") {
            let p = p
                .trim_start()
                .strip_prefix('=')
                .ok_or("expected `priority = N`")?;
            priority = p
                .trim()
                .parse()
                .map_err(|_| format!("priority `{}` is not an integer", p.trim()))?;
        } else {
            scope = match part {
                "Runtime" => Scope::Runtime,
                "Editor" => Scope::Editor,
                other => return Err(format!("unknown scope `{other}`")),
            };
        }
    }
    Ok((ty, scope, priority))
}

/// Map module path → feature gating it, from `#[cfg(feature = "x")] pub mod y;`
/// pairs across a crate's sources. Only the immediately preceding attribute line
/// is considered, which is how every gated module in this workspace is written.
fn module_gates(src: &Path) -> Result<BTreeMap<String, String>, String> {
    let mut gates = BTreeMap::new();
    for file in rust_files(src)? {
        let prefix = module_path(src, &file);
        let text = read(&file)?;
        let mut pending: Option<String> = None;
        for line in text.lines() {
            let t = line.trim();
            if let Some(feat) = cfg_feature(t) {
                pending = Some(feat);
                continue;
            }
            if let Some(name) = t
                .strip_prefix("pub mod ")
                .or_else(|| t.strip_prefix("mod "))
                .and_then(|r| r.strip_suffix(';'))
            {
                if let Some(feat) = pending.take() {
                    let full = if prefix.is_empty() {
                        name.trim().to_string()
                    } else {
                        format!("{prefix}::{}", name.trim())
                    };
                    gates.insert(full, feat);
                }
                continue;
            }
            if !t.is_empty() && !t.starts_with("//") && !t.starts_with("#[") {
                pending = None;
            }
        }
    }
    Ok(gates)
}

/// `#[cfg(feature = "x")]` → `x`. Deliberately narrow: a compound `cfg` isn't a
/// gate this generator knows how to reproduce, so it is ignored rather than
/// guessed at, and the resulting compile error names the file.
fn cfg_feature(line: &str) -> Option<String> {
    let rest = line.strip_prefix("#[cfg(feature = \"")?;
    let (feat, tail) = rest.split_once('"')?;
    tail.starts_with(")]").then(|| feat.to_string())
}

/// Every module feature guarding `path`, outermost first — a plugin inside
/// `a::b` needs both `a`'s and `b`'s gates.
fn gates_for(gates: &BTreeMap<String, String>, path: &str) -> Vec<String> {
    if path.is_empty() {
        return Vec::new();
    }
    let mut out = Vec::new();
    let mut acc = String::new();
    for seg in path.split("::") {
        if !acc.is_empty() {
            acc.push_str("::");
        }
        acc.push_str(seg);
        if let Some(f) = gates.get(&acc) {
            if !out.contains(f) {
                out.push(f.clone());
            }
        }
    }
    out
}

// ── Hosts ───────────────────────────────────────────────────────────────────

struct Host {
    dir: PathBuf,
    scope: Scope,
    install_fn: &'static str,
    app_path: &'static str,
    always: Option<&'static str>,
}

impl Host {
    /// Rewrite this host's manifest block and `plugins.rs`. Returns the files
    /// that changed (or, under `check`, that would change).
    fn write(&self, decls: &[Decl], check: bool) -> Result<Vec<String>, String> {
        let mine: Vec<&Decl> = decls.iter().filter(|d| d.scope == self.scope).collect();

        let manifest_path = self.dir.join("Cargo.toml");
        let manifest = read(&manifest_path)?;
        let new_manifest = self.rewrite_manifest(&manifest, &mine)?;

        // Gates are read back out of the *new* manifest, so a dependency this
        // run just added is described by the same source of truth as one that
        // has been hand-tuned for months.
        let features = feature_table(&new_manifest);
        let list_path = self.dir.join("src").join("plugins.rs");
        let new_list = self.render_list(&mine, &features);

        let mut changed = Vec::new();
        for (path, new) in [(manifest_path, new_manifest), (list_path, new_list)] {
            let old = std::fs::read_to_string(&path).unwrap_or_default();
            if normalize(&old) == normalize(&new) {
                continue;
            }
            changed.push(path.display().to_string());
            if !check {
                std::fs::write(&path, new.replace('\n', "\r\n"))
                    .map_err(|e| format!("write {}: {e}", path.display()))?;
            }
        }
        Ok(changed)
    }

    /// Ensure every declared crate has a dependency entry, adding the missing
    /// ones to the generated block and dropping entries for crates that no
    /// longer declare a plugin. Entries outside the block are never touched —
    /// that is how a hand-written `optional = true` + feature survives.
    fn rewrite_manifest(&self, text: &str, decls: &[&Decl]) -> Result<String, String> {
        let (before, block, after) = split_block(text)?;
        // Names present outside the generated block: already wired by hand.
        let manual = dep_names(&format!("{before}{after}"));

        let mut wanted: BTreeMap<&str, &str> = BTreeMap::new();
        for d in decls {
            if !manual.contains(&d.pkg) {
                wanted.insert(&d.pkg, &d.dep_path);
            }
        }

        if wanted.is_empty() {
            // Nothing to generate: drop the block entirely rather than leave an
            // empty pair of markers behind.
            return Ok(match block {
                Some(_) => format!("{before}{after}"),
                None => text.to_string(),
            });
        }

        let mut generated = String::new();
        let _ = writeln!(generated, "{BEGIN}");
        let _ = writeln!(
            generated,
            "# Discovered from their `renzora::add!` lines. Plain, non-optional\n\
             # entries: a new plugin is always compiled and always installed. To let\n\
             # the lean exporter strip one, move its line out of this block, mark it\n\
             # `optional = true`, and put it in a feature — the generator will leave\n\
             # it alone and read the gate back from there.\n\
             #\n\
             # Delete a plugin with `cargo renzora remove <crate>`, not by hand: an\n\
             # entry here pointing at a directory that no longer exists stops cargo\n\
             # loading the workspace, including to run the generator that would fix\n\
             # it. If you hit that, delete the offending line below."
        );
        for (pkg, path) in &wanted {
            let _ = writeln!(generated, "{pkg} = {{ path = \"{path}\" }}");
        }
        let _ = writeln!(generated, "{END}");

        Ok(insert_block(text, &generated))
    }

    /// Render `plugins.rs`.
    fn render_list(&self, decls: &[&Decl], features: &Features) -> String {
        let mut s = String::new();
        let scope = match self.scope {
            Scope::Runtime => "Runtime",
            Scope::Editor => "Editor",
        };
        let _ = writeln!(
            s,
            "//! GENERATED by `cargo renzora sync` — do not edit.\n\
             //!\n\
             //! The {scope}-scope plugin list, one entry per `renzora::add!(..,\n\
             //! {scope})` found under `crates/`. Edit the declaration in the plugin's\n\
             //! own crate, not this file; `cargo renzora sync --check` fails CI if\n\
             //! this file and those declarations disagree.\n\
             //!\n\
             //! A `#[cfg]` here mirrors the manifest: either the feature that enables\n\
             //! the crate's optional dependency, or a feature gating the module the\n\
             //! plugin is defined in. Ungated entries are always compiled in.\n"
        );
        // Most plugin types are unit structs, where `::default()` is redundant.
        // Writing `Type` for those and `Type::default()` for the rest would mean
        // parsing each crate's struct definitions to tell them apart, and getting
        // it wrong is a compile error in a file nobody wrote. `add!` requires
        // `Default` precisely so one spelling always works; the old macro got the
        // same exemption for free by being macro-expanded.
        let _ = writeln!(s, "#![allow(clippy::default_constructed_unit_structs)]\n");
        let _ = writeln!(s, "use {};\n", self.app_path);
        let _ = writeln!(
            s,
            "/// Install every {scope}-scope plugin. Entries are ordered by the\n\
             /// `priority` given to `add!` (lower first, default 0), then by path."
        );
        let _ = writeln!(s, "pub(crate) fn {}(app: &mut App) {{", self.install_fn);
        for d in decls {
            for gate in self.gates(d, features) {
                let _ = writeln!(s, "    #[cfg(feature = \"{gate}\")]");
            }
            let _ = writeln!(s, "    app.add_plugins({}::default());", d.path);
        }
        let _ = writeln!(s, "}}");
        s
    }

    /// The `cfg(feature = ..)` gates an install line needs, in manifest terms.
    fn gates(&self, d: &Decl, features: &Features) -> Vec<String> {
        let mut out = Vec::new();
        if let Some(f) = features.enabling_dep(&d.pkg) {
            out.push(f);
        }
        for local in &d.module_features {
            // A module feature is crate-local; find whichever host feature
            // forwards it (`game_ui = ["renzora_ember/game_ui"]`).
            if let Some(f) = features.forwarding(&d.pkg, local) {
                if !out.contains(&f) {
                    out.push(f);
                }
            }
        }
        out.retain(|f| Some(f.as_str()) != self.always);
        out
    }
}

// ── Manifest text surgery ───────────────────────────────────────────────────
//
// Line-based on purpose. xtask has no dependencies (see its Cargo.toml) and a
// TOML round-trip that preserves the comments in these two heavily-annotated
// manifests would need one. The generator only ever inserts or replaces its own
// marker-delimited block, so it never has to understand the rest of the file.

/// Split a manifest into (before, generated block, after).
fn split_block(text: &str) -> Result<(String, Option<String>, String), String> {
    let Some(start) = text.find(BEGIN) else {
        return Ok((text.to_string(), None, String::new()));
    };
    let end = text[start..]
        .find(END)
        .ok_or("generated block has no end marker — restore or delete it by hand")?;
    let end = start + end + END.len();
    let end = text[end..]
        .find('\n')
        .map(|n| end + n + 1)
        .unwrap_or(text.len());
    Ok((
        text[..start].to_string(),
        Some(text[start..end].to_string()),
        text[end..].to_string(),
    ))
}

/// Replace the generated block, or append it at the end of `[dependencies]`.
fn insert_block(text: &str, generated: &str) -> String {
    if let Ok((before, Some(_), after)) = split_block(text) {
        return format!("{before}{generated}{after}");
    }
    let lines: Vec<&str> = text.lines().collect();
    let mut out = String::new();
    let mut in_deps = false;
    let mut placed = false;
    for line in &lines {
        let t = line.trim();
        if in_deps && t.starts_with('[') {
            // Next section begins — the block belongs just above it. `generated`
            // already ends in a newline; adding another would leave a blank line
            // behind every time the block is inserted and removed again.
            out.push_str(generated);
            in_deps = false;
            placed = true;
        }
        if t == "[dependencies]" {
            in_deps = true;
        }
        let _ = writeln!(out, "{line}");
    }
    if !placed {
        out.push('\n');
        out.push_str(generated);
    }
    out
}

/// Dependency keys declared in `[dependencies]`.
fn dep_names(text: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut in_deps = false;
    for line in text.lines() {
        let t = line.trim();
        if t.starts_with('[') {
            in_deps = t == "[dependencies]";
            continue;
        }
        if !in_deps || t.starts_with('#') || t.is_empty() {
            continue;
        }
        if let Some((name, _)) = t.split_once('=') {
            let name = name.trim();
            if !name.is_empty() && !name.contains(' ') {
                out.push(name.to_string());
            }
        }
    }
    out
}

/// The `[features]` table, flattened to (feature, entries).
struct Features(Vec<(String, Vec<String>)>);

impl Features {
    /// Which feature turns on `dep:<pkg>`, if any.
    fn enabling_dep(&self, pkg: &str) -> Option<String> {
        let want = format!("dep:{pkg}");
        self.0
            .iter()
            .find(|(_, items)| items.contains(&want))
            .map(|(name, _)| name.clone())
    }

    /// Which feature forwards `<pkg>/<feat>` (including the optional `?` form),
    /// if any.
    fn forwarding(&self, pkg: &str, feat: &str) -> Option<String> {
        let plain = format!("{pkg}/{feat}");
        let opt = format!("{pkg}?/{feat}");
        self.0
            .iter()
            .find(|(_, items)| items.iter().any(|i| *i == plain || *i == opt))
            .map(|(name, _)| name.clone())
    }
}

/// Parse `[features]`, tolerating the multi-line arrays these manifests use.
fn feature_table(text: &str) -> Features {
    let mut out = Vec::new();
    let mut in_features = false;
    let mut current: Option<(String, String)> = None;
    for line in text.lines() {
        let t = line.trim();
        if t.starts_with('[') && !t.starts_with("[[") {
            if let Some((name, body)) = current.take() {
                out.push((name, split_items(&body)));
            }
            in_features = t == "[features]";
            continue;
        }
        if !in_features {
            continue;
        }
        if let Some((name, body)) = current.as_mut() {
            body.push_str(t);
            if body.matches('[').count() <= body.matches(']').count() {
                let (name, body) = (name.clone(), body.clone());
                current = None;
                out.push((name, split_items(&body)));
            }
            continue;
        }
        if t.starts_with('#') || t.is_empty() {
            continue;
        }
        if let Some((name, rest)) = t.split_once('=') {
            let name = name.trim().to_string();
            let body = rest.trim().to_string();
            if body.matches('[').count() > body.matches(']').count() {
                current = Some((name, body));
            } else {
                out.push((name, split_items(&body)));
            }
        }
    }
    if let Some((name, body)) = current {
        out.push((name, split_items(&body)));
    }
    Features(out)
}

/// `["a", "b"]` → `["a", "b"]`, ignoring trailing commas and inline comments.
fn split_items(body: &str) -> Vec<String> {
    body.trim()
        .trim_start_matches('[')
        .trim_end_matches(']')
        .split(',')
        .filter_map(|s| {
            let s = s.trim();
            let s = s.split('#').next().unwrap_or(s).trim();
            let s = s.trim_matches('"');
            (!s.is_empty()).then(|| s.to_string())
        })
        .collect()
}

// ── Filesystem helpers ──────────────────────────────────────────────────────

fn crate_dirs(root: &Path) -> Result<Vec<PathBuf>, String> {
    let mut out = Vec::new();
    let rd = std::fs::read_dir(root).map_err(|e| format!("read {}: {e}", root.display()))?;
    for entry in rd.flatten() {
        if !entry.file_type().map(|t| t.is_dir()).unwrap_or(false) {
            continue;
        }
        let dir = entry.path();
        if dir.join("Cargo.toml").is_file() {
            out.push(dir.clone());
        }
        // Nested editor subcrate (`crates/renzora_foo/editor`). One level only —
        // that is the whole convention, and walking deeper would wander into
        // vendored workspaces.
        let nested = dir.join("editor");
        if nested.join("Cargo.toml").is_file() {
            out.push(nested);
        }
    }
    out.sort();
    Ok(out)
}

fn rust_files(src: &Path) -> Result<Vec<PathBuf>, String> {
    let mut out = Vec::new();
    let mut stack = vec![src.to_path_buf()];
    while let Some(dir) = stack.pop() {
        let rd = std::fs::read_dir(&dir).map_err(|e| format!("read {}: {e}", dir.display()))?;
        for entry in rd.flatten() {
            let p = entry.path();
            if entry.file_type().map(|t| t.is_dir()).unwrap_or(false) {
                stack.push(p);
            } else if p.extension().is_some_and(|e| e == "rs") {
                out.push(p);
            }
        }
    }
    out.sort();
    Ok(out)
}

/// `src/lib.rs` → ``, `src/a.rs` → `a`, `src/a/mod.rs` → `a`, `src/a/b.rs` → `a::b`.
fn module_path(src: &Path, file: &Path) -> String {
    let rel = file.strip_prefix(src).unwrap_or(file);
    let mut parts: Vec<String> = rel
        .components()
        .map(|c| c.as_os_str().to_string_lossy().into_owned())
        .collect();
    let last = parts.pop().unwrap_or_default();
    let stem = last.trim_end_matches(".rs");
    if stem != "mod" && stem != "lib" && stem != "main" {
        parts.push(stem.to_string());
    }
    parts.join("::")
}

fn dependency_path(repo: &Path, dir: &Path) -> Result<String, String> {
    let relative = dir
        .strip_prefix(repo)
        .map_err(|_| format!("plugin crate escapes repository: {}", dir.display()))?;
    if let Ok(crate_relative) = relative.strip_prefix("crates") {
        return Ok(format!(
            "../{}",
            crate_relative.to_string_lossy().replace('\\', "/")
        ));
    }
    Ok(format!(
        "../../{}",
        relative.to_string_lossy().replace('\\', "/")
    ))
}

fn rel_display(repo: &Path, p: &Path) -> String {
    p.strip_prefix(repo)
        .unwrap_or(p)
        .to_string_lossy()
        .replace('\\', "/")
}

fn package_name(manifest: &str) -> Option<String> {
    let mut in_package = false;
    for line in manifest.lines() {
        let t = line.trim();
        if t.starts_with('[') {
            in_package = t == "[package]";
            continue;
        }
        if in_package {
            if let Some(rest) = t.strip_prefix("name") {
                if let Some((_, v)) = rest.split_once('=') {
                    return Some(v.trim().trim_matches('"').to_string());
                }
            }
        }
    }
    None
}

/// Read a file with line endings normalized to `\n`.
///
/// Every manifest edit below splices generated text into text read back off
/// disk, and Windows checkouts are CRLF. Normalizing on the way in means there
/// is exactly one line-ending convention in memory and exactly one conversion,
/// on write — rather than a rewrite that turns each existing `\r\n` into
/// `\r\r\n` and reports the whole file as changed.
fn read(p: &Path) -> Result<String, String> {
    std::fs::read_to_string(p)
        .map(|s| normalize(&s))
        .map_err(|e| format!("read {}: {e}", p.display()))
}

fn normalize(s: &str) -> String {
    s.replace("\r\n", "\n")
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::sync::atomic::{AtomicU64, Ordering};

    use super::*;

    static SEQUENCE: AtomicU64 = AtomicU64::new(0);

    struct TestRepo(PathBuf);

    impl TestRepo {
        fn new() -> Self {
            let root = std::env::temp_dir().join(format!(
                "renzora-sync-{}-{}",
                std::process::id(),
                SEQUENCE.fetch_add(1, Ordering::Relaxed)
            ));
            fs::create_dir_all(root.join("crates")).expect("test repo");
            Self(root)
        }

        fn crate_with(&self, relative: &str, package: &str, declaration: &str) {
            let root = self.0.join(relative);
            fs::create_dir_all(root.join("src")).expect("crate source");
            fs::write(
                root.join("Cargo.toml"),
                format!("[package]\nname = \"{package}\"\nversion = \"0.1.0\"\n"),
            )
            .expect("manifest");
            fs::write(root.join("src/lib.rs"), declaration).expect("source");
        }

        fn registry(&self, body: &str) {
            fs::create_dir_all(self.0.join("tier2")).expect("tier2");
            fs::write(self.0.join("tier2/plugins.toml"), body).expect("registry");
        }
    }

    impl Drop for TestRepo {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    #[test]
    fn source_checkout_without_registry_keeps_builtin_dependency_spelling() {
        let repo = TestRepo::new();
        repo.crate_with(
            "crates/renzora_weather",
            "renzora_weather",
            "renzora::add!(WeatherPlugin);\n",
        );

        let declarations = scan(&repo.0).expect("scan");

        assert_eq!(declarations.len(), 1);
        assert_eq!(declarations[0].dep_path, "../renzora_weather");
    }

    #[test]
    fn optional_builtin_gate_survives_sync_and_guards_installation() {
        let repo = TestRepo::new();
        repo.crate_with(
            "crates/renzora_weather",
            "renzora_weather",
            "renzora::add!(WeatherPlugin, Runtime);\n",
        );
        let host = repo.0.join("crates/renzora_runtime");
        fs::create_dir_all(host.join("src")).unwrap();
        let manifest = "[features]\ndefault = [\"weather\"]\nweather = [\"dep:renzora_weather\"]\n[dependencies]\nrenzora_weather = { path = \"../renzora_weather\", optional = true }\n";
        fs::write(host.join("Cargo.toml"), manifest).unwrap();
        let declarations = scan(&repo.0).unwrap();
        let host = Host {
            dir: host,
            scope: Scope::Runtime,
            install_fn: "install",
            app_path: "bevy::prelude::App",
            always: None,
        };
        host.write(&declarations, false).unwrap();
        let updated = fs::read_to_string(host.dir.join("Cargo.toml")).unwrap();
        assert!(updated.contains("optional = true"));
        let wiring = fs::read_to_string(host.dir.join("src/plugins.rs")).unwrap();
        assert!(wiring.contains("#[cfg(feature = \"weather\")]"));
        assert!(wiring.contains("renzora_weather::WeatherPlugin"));
        assert!(host.write(&declarations, true).unwrap().is_empty());
    }

    #[test]
    fn registered_tier2_halves_are_scanned_with_overlay_paths() {
        let repo = TestRepo::new();
        repo.crate_with(
            "tier2/com_example_weather/runtime",
            "weather_runtime",
            "renzora::add!(WeatherPlugin, Runtime);\n",
        );
        repo.crate_with(
            "tier2/com_example_weather/editor",
            "weather_editor",
            "renzora::add!(WeatherEditorPlugin, Editor);\n",
        );
        repo.registry(
            "schema = 1\n\n[[plugin]]\nid = \"com.example.weather\"\nruntime = \"tier2/com_example_weather/runtime\"\neditor = \"tier2/com_example_weather/editor\"\n",
        );

        let declarations = scan(&repo.0).expect("scan");

        assert_eq!(declarations.len(), 2);
        assert!(declarations
            .iter()
            .all(|decl| decl.dep_path.starts_with("../../tier2/")));
    }

    #[test]
    fn tier2_scope_mismatch_is_rejected() {
        let repo = TestRepo::new();
        repo.crate_with(
            "tier2/com_example_wrong/runtime",
            "wrong_runtime",
            "renzora::add!(WrongPlugin, Editor);\n",
        );
        repo.registry(
            "schema = 1\n\n[[plugin]]\nid = \"com.example.wrong\"\nruntime = \"tier2/com_example_wrong/runtime\"\n",
        );

        let error = scan(&repo.0).expect_err("scope mismatch");

        assert!(error.contains("Runtime crate declares a Editor plugin"));
    }

    #[test]
    fn tier2_path_escape_is_rejected() {
        let repo = TestRepo::new();
        repo.registry(
            "schema = 1\n\n[[plugin]]\nid = \"com.example.escape\"\nruntime = \"tier2/../outside\"\n",
        );

        let error = scan(&repo.0).expect_err("path escape");

        assert!(error.contains("unsafe Tier 2 registry path"));
    }

    #[test]
    fn duplicate_package_names_across_sources_are_rejected() {
        let repo = TestRepo::new();
        repo.crate_with(
            "crates/renzora_weather",
            "renzora_weather",
            "renzora::add!(BuiltInPlugin);\n",
        );
        repo.crate_with(
            "tier2/com_example_weather/runtime",
            "renzora_weather",
            "renzora::add!(ExternalPlugin, Runtime);\n",
        );
        repo.registry(
            "schema = 1\n\n[[plugin]]\nid = \"com.example.weather\"\nruntime = \"tier2/com_example_weather/runtime\"\n",
        );

        let error = scan(&repo.0).expect_err("package collision");

        assert!(error.contains("package name `renzora_weather` resolves to both"));
    }

    #[test]
    fn sync_wires_registered_halves_into_their_separate_hosts() {
        let repo = TestRepo::new();
        for host in ["renzora_runtime", "renzora_editor"] {
            let root = repo.0.join("crates").join(host);
            fs::create_dir_all(root.join("src")).expect("host source");
            fs::write(root.join("Cargo.toml"), "[dependencies]\n").expect("host manifest");
        }
        repo.crate_with(
            "tier2/com_example_weather/runtime",
            "weather_runtime",
            "renzora::add!(WeatherPlugin, Runtime);\n",
        );
        repo.crate_with(
            "tier2/com_example_weather/editor",
            "weather_editor",
            "renzora::add!(WeatherEditorPlugin, Editor);\n",
        );
        repo.registry(
            "schema = 1\n\n[[plugin]]\nid = \"com.example.weather\"\nruntime = \"tier2/com_example_weather/runtime\"\neditor = \"tier2/com_example_weather/editor\"\n",
        );

        sync(&repo.0, false).expect("sync");

        let runtime_manifest = fs::read_to_string(repo.0.join("crates/renzora_runtime/Cargo.toml"))
            .expect("runtime manifest");
        let runtime_plugins =
            fs::read_to_string(repo.0.join("crates/renzora_runtime/src/plugins.rs"))
                .expect("runtime plugins");
        let editor_manifest = fs::read_to_string(repo.0.join("crates/renzora_editor/Cargo.toml"))
            .expect("editor manifest");
        let editor_plugins =
            fs::read_to_string(repo.0.join("crates/renzora_editor/src/plugins.rs"))
                .expect("editor plugins");
        assert!(runtime_manifest
            .contains("weather_runtime = { path = \"../../tier2/com_example_weather/runtime\" }"));
        assert!(runtime_plugins.contains("weather_runtime::WeatherPlugin::default()"));
        assert!(!runtime_plugins.contains("WeatherEditorPlugin"));
        assert!(editor_manifest
            .contains("weather_editor = { path = \"../../tier2/com_example_weather/editor\" }"));
        assert!(editor_plugins.contains("weather_editor::WeatherEditorPlugin::default()"));
        assert!(!editor_plugins.contains("weather_runtime::WeatherPlugin"));
        sync(&repo.0, true).expect("generated files are stable");
    }
}
